package io.swagger.petstore.assertions.pet;

import io.swagger.petstore.models.pet.PetNotFoundModel;
import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link PetNotFoundModel} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractPetNotFoundModelAssert<S extends AbstractPetNotFoundModelAssert<S, A>, A extends PetNotFoundModel> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractPetNotFoundModelAssert}</code> to make assertions on actual PetNotFoundModel.
   * @param actual the PetNotFoundModel we want to make assertions on.
   */
  protected AbstractPetNotFoundModelAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual PetNotFoundModel's code is equal to the given one.
   * @param code the given code to compare the actual PetNotFoundModel's code to.
   * @return this assertion object.
   * @throws AssertionError - if the actual PetNotFoundModel's code is not equal to the given one.
   */
  public S hasCode(Integer code) {
    // check that actual PetNotFoundModel we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting code of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Integer actualCode = actual.getCode();
    if (!Objects.areEqual(actualCode, code)) {
      failWithMessage(assertjErrorMessage, actual, code, actualCode);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual PetNotFoundModel's message is equal to the given one.
   * @param message the given message to compare the actual PetNotFoundModel's message to.
   * @return this assertion object.
   * @throws AssertionError - if the actual PetNotFoundModel's message is not equal to the given one.
   */
  public S hasMessage(String message) {
    // check that actual PetNotFoundModel we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting message of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualMessage = actual.getMessage();
    if (!Objects.areEqual(actualMessage, message)) {
      failWithMessage(assertjErrorMessage, actual, message, actualMessage);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual PetNotFoundModel's type is equal to the given one.
   * @param type the given type to compare the actual PetNotFoundModel's type to.
   * @return this assertion object.
   * @throws AssertionError - if the actual PetNotFoundModel's type is not equal to the given one.
   */
  public S hasType(String type) {
    // check that actual PetNotFoundModel we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting type of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualType = actual.getType();
    if (!Objects.areEqual(actualType, type)) {
      failWithMessage(assertjErrorMessage, actual, type, actualType);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
