package io.swagger.petstore.assertions.pet;

import io.swagger.petstore.models.pet.Category;
import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link Category} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractCategoryAssert<S extends AbstractCategoryAssert<S, A>, A extends Category> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractCategoryAssert}</code> to make assertions on actual Category.
   * @param actual the Category we want to make assertions on.
   */
  protected AbstractCategoryAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual Category's id is equal to the given one.
   * @param id the given id to compare the actual Category's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Category's id is not equal to the given one.
   */
  public S hasId(int id) {
    // check that actual Category we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // check
    int actualId = actual.getId();
    if (actualId != id) {
      failWithMessage(assertjErrorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual Category's name is equal to the given one.
   * @param name the given name to compare the actual Category's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Category's name is not equal to the given one.
   */
  public S hasName(String name) {
    // check that actual Category we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
