package io.swagger.petstore.assertions.pet;

import io.swagger.petstore.models.pet.PetModel;
import org.assertj.core.api.AbstractComparableAssert;

/**
 * Abstract base class for {@link PetModel.Status} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractPetModelStatusAssert<S extends AbstractPetModelStatusAssert<S, A>, A extends PetModel.Status> extends AbstractComparableAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractPetModelStatusAssert}</code> to make assertions on actual PetModel.Status.
   * @param actual the PetModel.Status we want to make assertions on.
   */
  protected AbstractPetModelStatusAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
