package io.swagger.petstore.assertions.pet;

import io.swagger.petstore.models.pet.PetModel;

/**
 * {@link PetModel} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractPetModelAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class PetModelAssert extends AbstractPetModelAssert<PetModelAssert, PetModel> {

  /**
   * Creates a new <code>{@link PetModelAssert}</code> to make assertions on actual PetModel.
   * @param actual the PetModel we want to make assertions on.
   */
  public PetModelAssert(PetModel actual) {
    super(actual, PetModelAssert.class);
  }

  /**
   * An entry point for PetModelAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myPetModel)</code> and get specific assertion with code completion.
   * @param actual the PetModel we want to make assertions on.
   * @return a new <code>{@link PetModelAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static PetModelAssert assertThat(PetModel actual) {
    return new PetModelAssert(actual);
  }
}
