package io.swagger.petstore.assertions.pet;

import io.swagger.petstore.models.pet.PetNotFoundModel;

/**
 * {@link PetNotFoundModel} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractPetNotFoundModelAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class PetNotFoundModelAssert extends AbstractPetNotFoundModelAssert<PetNotFoundModelAssert, PetNotFoundModel> {

  /**
   * Creates a new <code>{@link PetNotFoundModelAssert}</code> to make assertions on actual PetNotFoundModel.
   * @param actual the PetNotFoundModel we want to make assertions on.
   */
  public PetNotFoundModelAssert(PetNotFoundModel actual) {
    super(actual, PetNotFoundModelAssert.class);
  }

  /**
   * An entry point for PetNotFoundModelAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myPetNotFoundModel)</code> and get specific assertion with code completion.
   * @param actual the PetNotFoundModel we want to make assertions on.
   * @return a new <code>{@link PetNotFoundModelAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static PetNotFoundModelAssert assertThat(PetNotFoundModel actual) {
    return new PetNotFoundModelAssert(actual);
  }
}
