package io.swagger.petstore.assertions.pet;

import io.swagger.petstore.models.pet.TagsItem;

/**
 * {@link TagsItem} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractTagsItemAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class TagsItemAssert extends AbstractTagsItemAssert<TagsItemAssert, TagsItem> {

  /**
   * Creates a new <code>{@link TagsItemAssert}</code> to make assertions on actual TagsItem.
   * @param actual the TagsItem we want to make assertions on.
   */
  public TagsItemAssert(TagsItem actual) {
    super(actual, TagsItemAssert.class);
  }

  /**
   * An entry point for TagsItemAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myTagsItem)</code> and get specific assertion with code completion.
   * @param actual the TagsItem we want to make assertions on.
   * @return a new <code>{@link TagsItemAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static TagsItemAssert assertThat(TagsItem actual) {
    return new TagsItemAssert(actual);
  }
}
